/* Mishmeret content. Every teaching here is a draft in Rabbi Amichai's voice and is reviewed by him before it reaches a Kohen. */
window.MISHMERET = {
  brand: { name: "Mishmeret", he: "מִשְׁמֶרֶת", tagline: "For the Kohanim of today.", site: "https://www.kehunacademy.com", rambam: "https://www.kehunacademy.com/offers/7QyYoRYw/checkout", whatsapp: "" },

  watches: [
    ["Yehoyariv","יְהוֹיָרִיב"],["Yedayah","יְדַעְיָה"],["Charim","חָרִם"],["Se’orim","שְׂעֹרִים"],
    ["Malkiyah","מַלְכִּיָּה"],["Miyamin","מִיָּמִן"],["Hakotz","הַקּוֹץ"],["Aviyah","אֲבִיָּה"],
    ["Yeshua","יֵשׁוּעַ"],["Shechanyahu","שְׁכַנְיָהוּ"],["Elyashiv","אֶלְיָשִׁיב"],["Yakim","יָקִים"],
    ["Chupah","חֻפָּה"],["Yeshevav","יֶשֶׁבְאָב"],["Bilgah","בִּלְגָּה"],["Imer","אִמֵּר"],
    ["Chezir","חֵזִיר"],["Hapitzetz","הַפִּצֵּץ"],["Petachyah","פְּתַחְיָה"],["Yechezkel","יְחֶזְקֵאל"],
    ["Yachin","יָכִין"],["Gamul","גָּמוּל"],["Delayahu","דְּלָיָהוּ"],["Ma’azyahu","מַעַזְיָהוּ"]
  ],

  /* Weeks of Tamid. days[0] is Sunday. Each day has a morning and an afternoon. A week with a start date (YYYY-MM-DD, a Sunday) is used for that week; otherwise the app rotates through the weeks it has. */
  weeks: [
    { label: "Week one", days: [
      { morning: { he: "אֶת־הַכֶּבֶשׂ אֶחָד תַּעֲשֶׂה בַבֹּקֶר וְאֵת הַכֶּבֶשׂ הַשֵּׁנִי תַּעֲשֶׂה בֵּין הָעַרְבָּיִם", en: "\"The one lamb you shall offer in the morning, and the second lamb you shall offer at bein ha’arbayim.\"", ref: "Bamidbar 28:4", teach: "The day in the Mikdash did not begin with whatever came first. It began with the Tamid. Before any private offering, before any request, the Kohen gave something that was not about him. That is the whole teaching of the morning Tamid, and it is small enough to do. Before the phone, before the emails, before the day takes you, place one thing first. Not a big thing. A constant one. Tamid means constant.", q: "What is the one thing you will offer first this morning, before anything asks you for something?" },
        afternoon: { he: "תִּכּוֹן תְּפִלָּתִי קְטֹרֶת לְפָנֶיךָ מַשְׂאַת כַּפַּי מִנְחַת־עָרֶב", en: "\"Let my prayer be set before You as incense, the lifting of my hands as the evening offering.\"", ref: "Tehillim 141:2", teach: "Bein ha’arbayim. Between the evenings. The light has not gone, but it is going. Our sages teach that Minchah was set to correspond to the Tamid of the afternoon. This is the hour that is hardest to give, because the day has already spent us. David asks that the lifting of his hands be received like the evening offering. For a Kohen, lifted hands are not a metaphor. Take one minute at the window while the light changes. Ask what the day took, and what is still yours to give.", q: "What is still yours to give, now, at the end of the day?" } },
      { morning: { he: "וְאַתָּה וּבָנֶיךָ אִתְּךָ תִּשְׁמְרוּ אֶת־כְּהֻנַּתְכֶם", en: "\"And you and your sons with you shall keep your priesthood.\"", ref: "Bamidbar 18:7", teach: "Not inherit. Keep. Tishmeru, the same root as mishmeret, a watch. You received the Kehuna at birth and there was nothing to do about it. A kept Kehuna is a different thing. It is one that someone is actually standing over, the way a guard watches a gate at night.", q: "Where in your ordinary week are you already standing watch, without calling it that?" },
        afternoon: { he: "שְׁמִירַת הַמִּקְדָּשׁ מִצְוַת עֲשֵׂה, וְאַף עַל פִּי שֶׁאֵין שָׁם פַּחַד מֵאוֹיְבִים", en: "\"Guarding the Mikdash is a positive mitzvah, even though there is no fear of enemies there.\"", ref: "Rambam, Beit HaBechira 8:1", teach: "The Rambam says the guards were not there because of danger. They were there because a palace with guards is not the same as a palace without them. The guarding itself was the honor. Twenty-four posts, all night, every night.", q: "What in your life is worth guarding tonight even though nothing is threatening it?" } },
      { morning: { he: "כֹּה תְבָרְכוּ אֶת־בְּנֵי יִשְׂרָאֵל", en: "\"Thus you shall bless the children of Israel.\"", ref: "Bamidbar 6:23", teach: "The Sifrei teaches that the Kohanim bless with a full heart. Not a formula recited, a blessing meant. And the verse after the blessing says, \"and I will bless them.\" The blessing is G-d’s. The Kohen is the open hand it passes through.", q: "Whom will you bless today, with a full heart, without saying a word?" },
        afternoon: { he: "הֱוֵי מִתַּלְמִידָיו שֶׁל אַהֲרֹן, אוֹהֵב שָׁלוֹם וְרוֹדֵף שָׁלוֹם", en: "\"Be of the disciples of Aharon, loving peace and pursuing peace.\"", ref: "Avot 1:12", teach: "Hillel did not say be a Kohen. He said be a student of the first one. Aharon’s whole avodah outside the Mikdash was standing between two people who were not speaking. Not fixing it. Standing there.", q: "Who are two people you could stand between this week?" } },
      { morning: { he: "וְהָיוּ עַל לֵב אַהֲרֹן בְּבֹאוֹ לִפְנֵי יְיָ", en: "\"And they shall be upon Aharon’s heart when he comes before Hashem.\"", ref: "Shemot 28:30", teach: "The names of the twelve tribes were set into the Choshen, and the Torah says where Aharon carried them. Not on his shoulders only. On his heart. A Kohen goes in carrying people. Before you go into your day, there are names you are carrying too, whether you chose them or not.", q: "Whose name is on your heart this morning, and what would it mean to carry it in on purpose?" },
        afternoon: { he: "וְהָיָה אַהֲרֹן וּבָנָיו עֹשִׂים כֹּל", en: "\"And Aharon and his sons shall do everything.\"", ref: "Bamidbar 4:19, on the sons of Kehat", teach: "When the Kohathites carried the holiest vessels, they were not allowed to look at them uncovered. Aharon and his sons went in first and covered each one. The Kohen’s work was often the work of covering, of protecting what is holy from being handled carelessly.", q: "What did you cover today so that something holy would not be handled carelessly? What still needs covering before the day ends?" } },
      { morning: { he: "וְאֵשׁ הַמִּזְבֵּחַ תּוּקַד בּוֹ", en: "\"And the fire of the altar shall be kept burning on it.\"", ref: "Vayikra 6:2", teach: "The fire on the Mizbeach was never allowed to go out, and it was the Kohen’s job every morning to add wood before anything else. Not to light it. It was already burning. To keep it. Most of the Kehuna is like this. The fire is there. The work is the wood.", q: "What is one piece of wood you can add this morning to a fire that is already burning in you?" },
        afternoon: { he: "בְּעֶרֶב אַתָּה מְקַטֵּר", en: "\"In the evening you shall burn the incense.\"", ref: "From Shemot 30:8, on the Ketoret", teach: "Aharon burned the Ketoret twice a day, once in the morning when he tended the lamps and once at bein ha’arbayim when he lit them. The incense was the most inward part of the avodah, done alone, with no one watching. It left a scent and nothing else.", q: "What is one thing you can do this evening that no one will see and that leaves only a scent?" } },
      { morning: { he: "בְּהַעֲלֹתְךָ אֶת הַנֵּרֹת", en: "\"When you raise up the lamps.\"", ref: "Bamidbar 8:2", teach: "Rashi asks why the Torah says to raise the lamps rather than to light them. He answers: the Kohen holds the flame to the wick until the flame rises on its own. That is what a Kohen does with a person too. He stays until the light stands by itself.", q: "Who in your life needs you to hold the flame a little longer this morning, until it rises on its own?" },
        afternoon: { he: "שָׁלוֹם שָׁלוֹם לָרָחוֹק וְלַקָּרוֹב", en: "\"Peace, peace, to the one who is far and to the one who is near.\"", ref: "Yeshayahu 57:19", teach: "Erev Shabbat. The whole week of a Kohen ends where Birkat Kohanim ends, in shalom. The verse says it twice. The Sages read this as the one who is far first, and only then the one who is near. Peace begins with the person you have been avoiding.", q: "Before Shabbat comes in, who is the far one, and what is one word of peace you can send?" } },
      { morning: { he: "וְעָרַךְ אֹתוֹ לִפְנֵי יְיָ תָּמִיד", en: "\"And he shall arrange it before Hashem always.\"", ref: "Vayikra 24:8, on the Lechem HaPanim", teach: "Every Shabbat the Kohanim replaced the twelve loaves on the Shulchan, and the Torah says the old bread was still warm when it came off. A week is long, and the bread stayed fresh the whole time. The Kohen’s work on Shabbat was to arrange, not to bake. Everything was already there.", q: "What has stayed warm this whole week without your effort, and can you simply arrange it today?" },
        afternoon: { he: "וַיִּשָּׂא אַהֲרֹן אֶת יָדָיו אֶל הָעָם וַיְבָרְכֵם", en: "\"And Aharon lifted his hands toward the people and blessed them.\"", ref: "Vayikra 9:22", teach: "The first Birkat Kohanim in history happened on the eighth day of the Mishkan, at the end of the avodah, before the fire came down. Aharon did not wait to see whether it worked. He blessed first. That is the order. Bless, and then the fire.", q: "As Shabbat goes out, whom will you bless before you know whether it worked?" } }
    ] }
  ],

  /* Birkat Kohanim, Bamidbar 6:24-26. [word, plain meaning, gloss, inner kavana, gloss source label (undefined = Rashi)] */
  verses: [
    { count: "3 words", words: [
      ["יְבָרֶכְךָ","May He bless you.","That your possessions be blessed.","Blessing begins in the material. G-d does not bless an idea. He blesses your actual life, the one with bills and children and a body. If the blessing is for something that real, then the Kohen has to mean something that real when he says it."],
      ["יְיָ","The Name of mercy.","In the Mikdash the Kohanim blessed with the explicit Name; outside it, with the Name as it is read.","You say the Name, but the blessing is His. \"And I will bless them.\" Your job here is not to be the source. It is to be an open hand that does not close around what passes through it.","Mishnah Sotah 7:6"],
      ["וְיִשְׁמְרֶךָ","And guard you.","That thieves should not come and take your possessions. A person who gives a gift to his servant cannot guard it for him from everyone. The Holy One both gives and guards.","Shamar is the root of mishmeret. What you receive needs keeping. So the first verse already holds the whole path: to be given something, and to stand watch over it."]
    ]},
    { count: "5 words", words: [
      ["יָאֵר","May He shine.","He will show you a smiling face, a shining face.","The light of a face is the feeling of being seen with warmth. Every person you bless has been looked at coldly this week. Here you are asking for the opposite."],
      ["יְיָ","The Name.","","The Name appears in each of the three verses. Chesed, then light, then peace. The same G-d, three ways of turning toward a person.",""],
      ["פָּנָיו","His face.","","Panim and pnim share their letters, face and inside. When a face shines, what is inside is showing. This is wordplay, not etymology, and it still teaches.",""],
      ["אֵלֶיךָ","Toward you.","","Not a general light. A light aimed at one person. When you say this word, there is someone in front of you it is aimed at.",""],
      ["וִיחֻנֶּךָּ","And be gracious to you.","He will give you grace.","Chen is being received before you have earned it. Most of us are still trying to earn it. This word says: stop for a moment, and be received."]
    ]},
    { count: "7 words", words: [
      ["יִשָּׂא","May He lift.","He will hold back His anger.","To lift a face is to look up at someone again after a rupture. This is the blessing for whoever in the room is carrying a broken relationship, with a person or with G-d."],
      ["יְיָ","The Name.","","The third time. By now the Kohen has said the Name three times with the same hands raised. Notice whether it is still alive in your mouth.",""],
      ["פָּנָיו","His face.","","A face that was turned away is turning back. That is what the whole third verse is about.",""],
      ["אֵלֶיךָ","Toward you.","","Again, aimed. Someone specific.",""],
      ["וְיָשֵׂם","And place.","","Shalom is set down deliberately, like a vessel placed on a table. It does not float in. Someone puts it there.",""],
      ["לְךָ","For you.","","Not for the people in general. For you. The Kohen blesses a crowd, and the Torah keeps saying you, singular.",""],
      ["שָׁלוֹם","Peace.","\"The Holy One found no vessel that holds blessing for Israel except peace.\"","Everything before this word needs a vessel. Shalom is the vessel. It is no accident that Aharon, who loved peace and pursued it, is the one who blesses. The Kohen ends where his whole avodah lives.","Mishnah Uktzin 3:12"]
    ]}
  ],

  prep: [
    "Remove your shoes before washing.",
    "A Levi pours the water over your hands.",
    "Go up to the duchan during Retzeh, before the chazan reaches Modim.",
    "Face the aron until the chazan calls \"Kohanim,\" then turn to the people.",
    "Say each word only after the chazan reads it.",
    "Hands raised, fingers in the form, eyes lowered. The people do not look at your hands, and neither do you."
  ],

  kavana60: "The verse after the blessing says: וַאֲנִי אֲבָרְכֵם, \"and I will bless them.\" The blessing is not yours. You are the open hand it passes through. The Zohar in Naso teaches that the Shechinah rests upon the hands of the Kohanim while they bless. So before the first word, empty the hands. Nothing to prove, nothing to give from your own store. Then say the Name, and let the blessing go where it is sent.",

  weeklyQuestion: "Where in your week did you act as a Kohen, and nobody knew?",

  paths: [
    { id: "kehuna", title: "Mishmeret Kehuna", sub: "30 days", intro: "The Kohen today. What is kept, what is carried, and where the priesthood lives in a week that looks like everyone else’s. Each day is one source, one teaching, one question.",
      lessons: [
        { n: 1, title: "You and your sons: what is kept", state: "open", src: { he: "וְאַתָּה וּבָנֶיךָ אִתְּךָ תִּשְׁמְרוּ אֶת־כְּהֻנַּתְכֶם", en: "\"And you and your sons with you shall keep your priesthood.\"", ref: "Bamidbar 18:7" },
          body: ["The verse does not say you inherited your priesthood. It says you shall keep it. Tishmeru. The same root as mishmeret, a watch. A Kohen receives the Kehuna by birth, and there is nothing to do about that. A kept Kehuna is something else. It is a priesthood that someone is actually watching over, the way a guard watches a gate at night.", "So the question this whole path is asking is simple. What does it look like to keep a priesthood in a year with no Mikdash, no korbanot, and a day that looks like everyone else’s? We are going to answer it one piece at a time. Today, only notice this: you were given something to keep."],
          q: "Where in your ordinary week are you already standing watch, without calling it that?" },
        { n: 2, title: "The blessing you carry", state: "open", src: { he: "כֹּה תְבָרְכוּ אֶת־בְּנֵי יִשְׂרָאֵל אָמוֹר לָהֶם", en: "\"Thus you shall bless the children of Israel; say to them.\"", ref: "Bamidbar 6:23" },
          body: ["Fifteen words. Three, then five, then seven. Sixty letters. The Torah did not leave the Kohen to improvise the most important thing he says. It gave him the exact words, and then, a verse later, took the credit away from him: \"and I will bless them.\" The Kohen is the channel, not the source.", "Open the Duchan screen and go through the fifteen words slowly, one at a time. Do not try to hold all of them. Find the one word that is yours this week."],
          q: "Which of the fifteen words do you most need said to you right now?", link: "duchan" },
        { n: 3, title: "The cemetery and the boundary of life", state: "open", src: { he: "אֱמֹר אֶל־הַכֹּהֲנִים בְּנֵי אַהֲרֹן וְאָמַרְתָּ אֲלֵהֶם לְנֶפֶשׁ לֹא־יִטַּמָּא בְּעַמָּיו", en: "\"Speak to the Kohanim, the sons of Aharon, and say to them: none shall become impure for a dead person among his people.\"", ref: "Vayikra 21:1" },
          body: ["A Kohen does not enter a cemetery, does not stand within four amot of a grave, and does not come under one roof with the dead, unless the one who died is among his seven closest relatives. The Rambam sets it out in Hilchot Avel, chapter two and three, and the Shulchan Aruch in Yoreh De’ah 371. Every Kohen knows the feeling of standing outside the fence while everyone else walks in.", "Why would the Torah build a fence between the Kohen and death? The Kohen stands at the altar, and the altar is entirely on the side of life. Blood on the altar is life given, not life lost. The Kohen, who carries that avodah in his body even without a Mikdash, is kept on the side of life. Not because death is bad. Because his job is the other direction. The distance is not an exclusion. It is a statement about what you are for.", "The full article, with the questions people actually ask, is in the Ask screen under \"A Kohen and the cemetery.\" A specific case is always for your rav."],
          q: "The next time you stand at the edge of a cemetery, what does it mean that your priesthood is kept on the side of the living?" },
        { n: 4, title: "Whom a Kohen marries", state: "soon" },
        { n: 5, title: "Pidyon HaBen: the firstborn and the Kohen", state: "soon" },
        { n: 6, title: "Twenty-four gifts, then and now", state: "soon" },
        { n: 7, title: "Aharon: loving peace, pursuing peace", state: "soon" }
      ] },
    { id: "rambam", title: "Rambam, Hilchot Beit HaBechira", sub: "8 chapters, audio", intro: "The laws of the Temple, chapter by chapter, with Rabbi Amichai. Seven chapters are recorded. Listen on kehunacademy.com; the recordings live in the Beit Midrash there.",
      lessons: [
        { n: 1, title: "The Mikdash as a mitzvah, and its place", state: "audio" }, { n: 2, title: "The vessels: the Aron, the Menorah, the Shulchan", state: "audio" }, { n: 3, title: "The Mizbeach and its measures", state: "audio" }, { n: 4, title: "The courtyards and the chambers", state: "audio" }, { n: 5, title: "The gates and the walls", state: "audio" }, { n: 6, title: "Kedushah of the Mikdash and Jerusalem", state: "audio" }, { n: 7, title: "The order of the courtyard", state: "audio" }, { n: 8, title: "The guarding of the Mikdash", state: "text" }
      ] },
    { id: "inner", title: "The Inner Kehuna", sub: "3 sessions", intro: "Hod, Shalom, and the Kohen who owns no land. Drawn from Rabbi Amichai’s conversation with Eli on the inner meaning of the priesthood.",
      lessons: [ { n: 1, title: "Hod and the Kohen", state: "soon" }, { n: 2, title: "The one who owns no land", state: "soon" }, { n: 3, title: "Shalom as avodah", state: "soon" } ] }
  ],

  chips: [
    ["Why does the Kohen own no land?", "Why does the Kohen not own land?"],
    ["The structure of Birkat Kohanim", "What is the structure of Birkat Kohanim, and why three verses?"],
    ["A Kohen and the cemetery", "What is the general rule about a Kohen and a cemetery?"],
    ["Hod and the Kohanim", "What is Hod and how does it connect to the Kohanim?"]
  ],

  prepared: [
    { k: /land|portion|inherit|nachal/i, a: "Because G-d Himself is the Kohen’s portion. Aharon is told, \"I am your portion and your inheritance among the children of Israel\" (Bamidbar 18:20), and Devarim 18:1–2 repeats it for the whole tribe. The Rambam explains (Shemitah veYovel 13:12) that Levi was set apart to serve G-d and to teach His ways, and so was freed from the wars and labors of the land, and then adds (13:13) that anyone whose spirit moves him to set himself apart to stand before G-d becomes holy of holies, and G-d becomes his portion. In the inner reading, a man who owns nothing is not a threat, so people can bring him what they are ashamed of.\nSources: Bamidbar 18:20; Devarim 18:1–2; Rambam, Shemitah veYovel 13:12–13; Live Kabbalah, \"The Kehuna\" (May 2025)." },
    { k: /birkat|bless|duchan|verse/i, a: "Birkat Kohanim is three verses (Bamidbar 6:24–26) of three, five and seven words, fifteen words and sixty letters in all. The first asks for blessing and its keeping; Rashi reads it as material blessing and protection from loss. The second asks for the light of G-d’s face and for grace. The third asks that G-d lift His face, which Rashi reads as holding back anger, and that He place peace. The Mishnah at the end of Uktzin says G-d found no vessel to hold blessing except peace, which is why the blessing ends there. The verse after, \"and I will bless them,\" makes clear the Kohen is the channel and not the source.\nSources: Bamidbar 6:22–27; Rashi there; Mishnah Uktzin 3:12; Mishnah Sotah 7:6." },
    { k: /cemeter|grave|dead|funeral|tum/i, a: "The general principle is in Vayikra 21:1–4. A Kohen may not make himself impure through contact with the dead, except for his seven close relatives: father, mother, son, daughter, brother, unmarried sister, and wife. The Rambam sets this out in Hilchot Avel, chapter 3. Impurity comes through touching, carrying, or being under one roof with the dead, so a Kohen keeps four amot from a grave and does not enter a cemetery; a wall ten tefachim high changes the distance rule (Yoreh De’ah 371). Questions about a specific funeral, a hospital, or the grave of a tzaddik have real differences of opinion, and your rav should decide the actual case.\nSources: Vayikra 21:1–4; Rambam, Hilchot Avel 2:1–7, 3:1–14; Rambam, Tumat Met 1:1; Shulchan Aruch, Yoreh De’ah 371." },
    { k: /hod|sefir|inner|shalom|aharon|peace/i, a: "In the Kabbalah, Aharon and the Kohanim are aligned with Hod, the sefirah of acknowledgment and surrender, the place where a person bows. Aharon is the one who \"loved peace and pursued peace\" (Avot 1:12), and the blessing he gives ends in shalom. In Rabbi Amichai’s conversation with Eli, the two ideas meet: the Kohen’s power is not force but bitul. He owns no land, he pursues no advantage, and so he can stand between two people who are not speaking. That standing between is the avodah of Hod, and it is available to a Kohen today without a Mikdash.\nSources: Avot 1:12; Bamidbar 6:26; Live Kabbalah, \"The Kehuna: Priesthood, Hod and the work of Shalom\" (May 2025). The mapping of Aharon to Hod is standard in Kabbalistic literature; ask for a specific citation if you need one." }
  ],

  rules: "You are the study companion inside Mishmeret, a learning community for Kohanim created by Rabbi Amichai Cohen of Live Kabbalah. Answer only questions about the Kehuna: the Kohanim, Birkat Kohanim, the Beit HaMikdash and its avodah, the Rambam’s Hilchot Beit HaBechira and related laws, and the inner meaning of the priesthood in Chassidus and Kabbalah. Ground every answer in named sources (a Torah verse with chapter and verse, Mishnah, Talmud, Rambam with the name of the halachot and chapter, Zohar, Tanya) and name them inline in the prose. Distinguish clearly between plain meaning, halacha, commentary, and inner teaching. Never rule on a personal halachic question. If a question is practical and personal (may I attend this funeral, may I marry this person, what should I do), state the general principle in one or two sentences and tell the person to bring the actual case to their rav. If you are not sure of a source, say so plainly rather than inventing one. Write G-d with a hyphen. Do not use contractions. No bullet lists, no headings. Warm, plain, grounded prose, at most 170 words. Finish with one line beginning \"Sources:\" listing what you drew on. If the question is outside the Kehuna, say gently that this companion only studies the Kehuna and offer one related direction."
};
